## Numpy 기초
### 202045062  김수민

- 머신러닝의 주요 알고리즘은 선형대수와 통계 기반
- Numerical Python = Numpy
- 대량 데이터의 배열 연산을 가능하게 함 → 빠른 연산 속도
- C/C++ 과 호환 API 제공
- 다양한 데이터 핸들링 기능 제공 주로 Pandas

### ndarray

#### import

In [1]:
import numpy as np

#### narray
- 넘파이의 기반 데이터 타입은 ndarray → 다차원 배열 생성 및 연산
    
    ![Untitled](ndarray.png)
    - 1차원 행렬은 (4, ) 뒤에를 안씀 왜냐면 세로로 세운거랑 다름 없음
    - 2차원은 (2,3)
    - 3차원은 (4,3,2)
    - 세로부터 인자 값을 준다
- 넘파이 array() 파이썬 리스트 같은 다양한 인자를 ndarray로 변환
- `.shape`는 `ndarray`의 크기를 튜플 형태로 가지고 있음

In [4]:
array1 = np.array([1,2,3])
print(f"array1 type : {type(array1)}")
print(f"array1 shape : {array1.shape}")

array2 = np.array([[1,2,3], [2,3,4]])
print(f"array2 type : {type(array2)}")
print(f"array2 shape : {array2.shape}")

array3 = np.array([[1,2,3]])
print(f"array3 type : {type(array3)}")
print(f"array3 shape : {array3.shape}")

array1 type : <class 'numpy.ndarray'>
array1 shape : (3,)
array2 type : <class 'numpy.ndarray'>
array2 shape : (2, 3)
array3 type : <class 'numpy.ndarray'>
array3 shape : (1, 3)


array1
  | 1 | 2 | 3 |
  | --- | --- | --- |

array2
  | 1 | 2 | 3 |
  | --- | --- | --- |
  | 2 | 3 | 4 |

array3
  | 1 | 2 | 3 |
  | --- | --- | --- |

  array1와 array3는 보이는 형태는 같지만 1차원 array와 2차원 array

#### ndim

In [41]:
print(array1.ndim, array2.ndim, array3.ndim)
print(f"array1 : {array1.ndim}차원, array2 : {array2.ndim}차원, array3: {array3.ndim}차원")

1 1 1
array1 : 1차원, array2 : 1차원, array3: 1차원


#### 데이터 타입
- ndarray 내 데이터 값은 숫자, 문자, bool 모두 가능
- 연산은 같은 데이터 타입만 가능 $int *float$ 불가
- .dtype 속성으로 확인가능

- 데이터 유형이 섞여있으면 크기가 더 큰 데이터 타입으로 일괄 적용
- int + string / int + float 리스트 ndarray 로 변경

In [8]:
list1 = {1,2,3}
print(type(list1))
array1 = np.array(list1)
print(type(array1))
array1, array1.dtype

<class 'set'>
<class 'numpy.ndarray'>


(array({1, 2, 3}, dtype=object), dtype('O'))

- u21 은 유니코드 형태

In [9]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


- int32 → float64 → int32
- `astype` 형변환

In [10]:
array_int = np.array([1,2,3])
array_float = array_int.astype("float64")
print(array_float, array_float.dtype)

array_int1 = array_float.astype("int32")
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype("int32")
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


#### arrange
- 특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성
- 주로 테스트용 데이터 또는 대규모 데이터 일괄 초기화 때 사용
- arrange() = range()와 유사
- array를 range로 표현

In [11]:
seq_array = np.arange(10)
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


#### zeros, ones
- zeros() → shape만 입력하면 모든값을 0으로 채운 ndrarray 반환
- ones() → shape갑승ㄹ 입력하면 모든값을 1으로 채운 ndrarray 반환
- .dtype으로 정해주지 않으면 기본적으로 float64

In [13]:
zero_array = np.zeros((3,2), dtype="int32")
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### reshape()
- ndarray를 특정 차원 및 크기로 변환
- 1차원 ndarray를 2*5 / 5*2 형태로 변환
- 지정된 사이즈로 변경이 불가능하면 오류 발생 - 개수가 맞아야됨

In [14]:
array1 = np.arange(10)
print("array1 : \n ", array1)

array2 = array1.reshape(2,5)
print("array2 : \n ", array2)

array3 = array1.reshape(5,2)
print("array3 : \n ", array3)

array1 : 
  [0 1 2 3 4 5 6 7 8 9]
array2 : 
  [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- 인자를 -1로 적용하면 ndarray와 호환되는 새로운 shape으로 변환

In [15]:
array1 = np.arange(10)
print("array1 : \n ", array1)

array2 = array1.reshape(-1,5)
print("array2 : \n ", array2)

array3 = array1.reshape(5,-1)
print("array3 : \n ", array3)

array1 : 
  [0 1 2 3 4 5 6 7 8 9]
array2 : 
  [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용
- reshape(-1, 1)원본은 ndarray가 어떤 형태라도 2차원이고 여러개의 로우를 가지게 되며 반드시 1개의 컬럼을 가진 ndarray로 변환됨을 보장

In [18]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print("array3d : \n", array3d.tolist())

# 3차원 -> 2차원 
array5 = array3d.reshape(-1,1)
print("array5 : \n", array5.tolist())
print("array5 shape: \n", array5.shape)

# 1차원 -> 2차원 
array6 = array1.reshape(-1,1)
print("array6 : \n", array6.tolist())
print("array6 shape: \n", array6.shape)

array3d : 
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: 
 (8, 1)
array6 : 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: 
 (8, 1)


#### ndarray의 데이터 인덱싱

1. 특정 데이터만 추출 - 해당 위치 인덱스 값 지정 시 해당 위치 데이터 변환
2. 슬리이싱
3. 팬시 인덱싱 - 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정하혀 해당 위치에 있는 데이터의 ndarray를 변환
4. 불린 인덱싱 - true/false 값 인덱싱 집합을 기반으로 trye에 해당하는 인덱싱 위치에 있는 데이터 ndarray를 반환

##### 일반 인덱싱
- array1[2] 은 데이터값

In [20]:
array1 = np.arange(start=1, stop=10)
print(array1)

value = array1[2]
print(value)
print(type(value))

print(f"맨뒤의 값 : {array1[-1]}, 맨뒤에서 두번째 값 : {array1[-2]}")

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int32'>
맨뒤의 값 : 9, 맨뒤에서 두번째 값 : 8


##### 데이터 값 바꾸기

In [21]:
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


##### 다차원 ndarray에서 단일값 추출

- 1차원 → 2차원 3*3으로 변환 후 2차원에서 추출

In [22]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print("row=0, col=0 : ", array2d[0,0])
print("row=0, col=1 : ", array2d[0,1])
print("row=1, col=0 : ", array2d[1,0])
print("row=1, col=1 : ", array2d[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
row=0, col=0 :  1
row=0, col=1 :  2
row=1, col=0 :  4
row=1, col=1 :  5


##### 슬라이싱하여 추출

In [23]:
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[9 2 3]
<class 'numpy.ndarray'>


In [24]:
array1 = np.arange(1,10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


##### 2차원 슬라이싱 인덱싱

- [row, col]

  |  | 0 | 1 | 2 |
  | --- | --- | --- | --- |
  | 0 | 1 | 2 | 3 |
  | 1 | 4 | 5 | 6 |
  | 2 | 7 | 8 | 9 |

In [26]:
# 2차원 인덱싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d : \n',array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


##### 팬시인덱싱

- array2[[0,1],2]로우측에 팬시 인덱싱 [0,1] 을 컬럼축에 인덱싱2를 적용 → row, col인덱스가 적용되어 3,6 반환

In [25]:
print('array2d : \n',array2d.tolist())
array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d : 
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


##### 불린 인덱싱

- 조건 필터링과 검색을 동시에 가능

In [27]:
array1d = np.arange(1, 10)
array2 = array1d[array1d > 6]

print('array1d > 5 불린 인덱싱 값 : ', array2)

array1d > 5 불린 인덱싱 값 :  [7 8 9]


In [30]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array3 = array1d[boolean_indexes]
print("불린 인덱싱 필터링 결과", array3)

indexes = np.array([5,6,7,8])
array4 = array1[indexes]
print("일반 인덱싱 필터링 결과", array4)

불린 인덱싱 필터링 결과 [6 7 8 9]
일반 인덱싱 필터링 결과 [6 7 8 9]


##### 행렬의 정렬 sort(), argsort()

- `sort()` → 결과만 반환, `ndarray.sort()` → 정렬을 아예 해버림

In [34]:
# np.sort
org_array = np.array([3,1,9,5])
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 : ',sort_array1)
print('np.sort() 호출 후 원본 행렬 : ',org_array)

# ndarray.sort
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 : ',sort_array2)
print('org_array.sort() 호출 후 원본 행렬 : ',org_array)

np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 :  None
org_array.sort() 호출 후 원본 행렬 :  [1 3 5 9]


- 내림 차순은 `::1`
- 로우와 칼럼은 `axis=0`, `axis=1`

In [35]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 : ', sort_array1_desc)

# 로우,칼럼 방향으로 정렬
array2d = np.array([[8, 12], [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬 : \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬 : \n', sort_array2d_axis1)

내림차순으로 정렬 :  [9 5 3 1]
로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


- 정렬된 행렬의 인덱스 반환

In [39]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices)

# 내림차순
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 : ',sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


##### 행렬 곱 np.dot()

In [37]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8], [9,10], [11,12]])

print('행렬 내적 결과 : \n', np.dot(A,B))

행렬 내적 결과 : 
 [[ 58  64]
 [139 154]]


##### 전치 행렬 transpose()

In [40]:
A1 = np.array([[1,2],[3,4]])
print('A1의 전치 행렬 : \n', np.transpose(A1))
print('A의 전치 행렬 : \n', np.transpose(A))
print('B의 전치 행렬 : \n', np.transpose(B))

A1의 전치 행렬 : 
 [[1 3]
 [2 4]]
A의 전치 행렬 : 
 [[1 4]
 [2 5]
 [3 6]]
B의 전치 행렬 : 
 [[ 7  9 11]
 [ 8 10 12]]
